FROM nginx:alpine

# Copie des fichiers statiques du Dashboard
COPY sdk-python/intermesh/console/ /usr/share/nginx/html/

# Copie de la configuration Nginx
COPY docker/nginx-dashboard.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
